version: '3.8'

services:
  mariadb-columnstore:
    image: mariadb/columnstore:latest
    container_name: mariadb-columnstore
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mysql-airflow:
    image: mysql:8.0
    container_name: mysql-airflow
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflowpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_airflow_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://airflow:airflowpass@mysql-airflow:3306/airflow
      AIRFLOW_CONN_MARIADB_CONN: mysql://sonu:Yunachan10@mariadb-columnstore:3306/shoppers_db
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./mlruns:/mlflow              # shared MLflow runs with MLflow server
      - ./artifacts:/opt/airflow/artifacts
      - ./reports:/opt/airflow/reports
    ports:
      - "8080:8080"
    depends_on:
      mariadb-columnstore:
        condition: service_healthy
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username sonu --firstname sonu --lastname jaiswal --role Admin --email jaiswalsonukr7@gmail.com --password Yunachan10 || true &&
      airflow webserver"
    restart: unless-stopped

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://airflow:airflowpass@mysql-airflow:3306/airflow
      AIRFLOW_UID: 50000
      AIRFLOW_CONN_MARIADB_CONN: mysql://sonu:Yunachan10@mariadb-columnstore:3306/shoppers_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./mlruns:/mlflow              # shared MLflow runs with MLflow server
      - ./artifacts:/opt/airflow/artifacts
      - ./reports:/opt/airflow/reports
    depends_on:
      airflow-webserver:
        condition: service_started
    command: airflow scheduler
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.0
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow             # shared MLflow runs
    command: >
      mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow --host 0.0.0.0
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/opt/airflow/artifacts
      - ./mlruns:/mlflow
    depends_on:
      - mariadb-columnstore
      - redis
      - mlflow
    restart: unless-stopped

  streamlit:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    restart: unless-stopped

volumes:
  mariadb_data:
  mysql_airflow_data:
  redis_data:
  airflow_artifacts:
